# Generated by Django 3.0.8 on 2021-04-29 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrecord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserRecord',
                'verbose_name_plural': 'UserRecords',
                'db_table': 'user_record',
                'ordering': ['-created_time'],
            },
        ),
    ]
