# Generated by Django 3.0.8 on 2021-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userrecord_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrecord',
            table='user_record',
        ),
    ]
