# Generated by Django 3.0.8 on 2021-04-27 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20210423_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrecord', to=settings.AUTH_USER_MODEL),
        ),
    ]
