# Generated by Django 3.2.3 on 2021-06-10 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210510_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'get_latest_by': 'measured_time', 'ordering': ['-measured_time'], 'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterField(
            model_name='data',
            name='measured_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
