# Generated by Django 3.2.3 on 2021-06-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210610_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='unit',
        ),
    ]
