# Generated by Django 3.0.8 on 2021-04-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_auto_20210423_1432'),
        ('data', '0003_auto_20210426_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='equipment.Equipment'),
        ),
    ]
