# Generated by Django 3.0.8 on 2021-04-27 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0004_auto_20210426_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensorrecord', to='data.Sensor')),
            ],
            options={
                'verbose_name': 'SensorRecord',
                'verbose_name_plural': 'SensorRecords',
                'db_table': 'sensor_record',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-created_time'], 'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.DeleteModel(
            name='Sensor_Record',
        ),
    ]
