# Generated by Django 3.0.8 on 2024-12-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_auto_20241216_2132'),
        ('data', '0005_alter_data_measured_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('sensor', 'measured_time')},
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['sensor'], name='data_sensor__5f75a2_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['measured_time'], name='data_measure_dfb089_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['created_time'], name='data_created_fa96c3_idx'),
        ),
    ]
