# Generated by Django 3.0.8 on 2021-04-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210427_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensorrecord',
            table='sensorrecord',
        ),
    ]
