# Generated by Django 3.0.8 on 2021-04-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210427_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorrecord',
            options={'verbose_name': 'SensorRecord', 'verbose_name_plural': 'SensorRecords'},
        ),
        migrations.RemoveField(
            model_name='sensorrecord',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='sensorrecord',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='sensorrecord',
            name='record',
        ),
        migrations.RemoveField(
            model_name='sensorrecord',
            name='sensor',
        ),
        migrations.AlterModelTable(
            name='sensorrecord',
            table='sensor_record',
        ),
    ]
