# Generated by Django 3.0.8 on 2021-04-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_auto_20210427_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorrecord',
            options={'ordering': ['-created_time'], 'verbose_name': 'SensorRecord', 'verbose_name_plural': 'SensorRecords'},
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='record',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensorrecord', to='data.Sensor'),
        ),
    ]
