# Generated by Django 3.0.8 on 2021-04-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210427_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-measured_time'], 'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
    ]
