# Generated by Django 3.0.8 on 2021-04-28 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_brief', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(choices=[('RE', 'Reactor')], default='RE', max_length=32)),
                ('descript', models.CharField(max_length=256, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'db_table': 'equipment',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentrecord', to='equipment.Equipment')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EquipmentRecord',
                'verbose_name_plural': 'EquipmentRecords',
                'db_table': 'equipment_record',
                'ordering': ['-created_time'],
            },
        ),
    ]
