# Generated by Django 3.0.8 on 2021-04-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_brief', models.CharField(max_length=64, unique=True)),
                ('key', models.CharField(max_length=16, unique=True)),
                ('type', models.CharField(choices=[('RE', 'Reactor')], default='RE', max_length=32)),
                ('descript', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('begin_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_inuse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_brief', models.CharField(max_length=64, unique=True)),
                ('key', models.CharField(max_length=16, unique=True)),
                ('descript', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.Equipment')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='SensorHistoricalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('key', models.CharField(max_length=16, unique=True)),
                ('descript', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.Equipment')),
                ('modifier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensorhistoricalrecord_modified', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Sensor')),
            ],
            options={
                'verbose_name': 'SensorHistoricalRecord',
                'verbose_name_plural': 'SensorHistoricalRecords',
                'ordering': ['-created_time'],
            },
        ),
    ]
