# Generated by Django 3.0.8 on 2021-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name_brief',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
