# Generated by Django 3.2.3 on 2021-05-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20210510_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='name_brief',
            new_name='abbreviation',
        ),
    ]
