# Generated by Django 3.0.8 on 2021-04-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20210416_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name_brief',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
