# Generated by Django 3.2.3 on 2021-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_rename_name_brief_equipment_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='key',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
