# Generated by Django 3.0.8 on 2021-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20210416_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='key',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='key',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorhistoricalrecord',
            name='key',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
