# Generated by Django 3.0.8 on 2021-04-16 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_auto_20210416_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='begin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='descript',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name_brief',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_inuse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='descript',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name_brief',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorhistoricalrecord',
            name='descript',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sensorhistoricalrecord',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.Equipment'),
        ),
        migrations.AlterField(
            model_name='sensorhistoricalrecord',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensorhistoricalrecord_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensorhistoricalrecord',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Sensor'),
        ),
    ]
