# Generated by Django 3.0.8 on 2024-12-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20241216_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
