# Generated by Django 3.0.8 on 2021-04-16 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0005_auto_20210416_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='user',
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ManyToManyField(null=True, related_name='equipment_inuse', to=settings.AUTH_USER_MODEL),
        ),
    ]
