# Generated by Django 3.0.8 on 2025-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20250729_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('RE', 'Reactor'), ('CP', 'Compass'), ('CP500', 'compostlab500')], default='RE', max_length=32),
        ),
    ]
