# Generated by Django 3.0.8 on 2021-04-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0010_auto_20210419_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorhistoricalrecord',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='sensorhistoricalrecord',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='sensorhistoricalrecord',
            name='key',
        ),
        migrations.RemoveField(
            model_name='sensorhistoricalrecord',
            name='name',
        ),
        migrations.AddField(
            model_name='sensorhistoricalrecord',
            name='record',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='EquipmentUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('users', models.ManyToManyField(null=True, related_name='equipmentusagerecord_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EquipmentUsageRecord',
                'verbose_name_plural': 'EquipmentUsageRecords',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistoricalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(blank=True, max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipmenthistoricalrecord_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EquipmentHistoricalRecord',
                'verbose_name_plural': 'EquipmentHistoricalRecords',
                'ordering': ['-created_time'],
            },
        ),
    ]
