# Generated by Django 3.0.8 on 2021-04-20 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0011_auto_20210420_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='equipment_inuse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentusagerecord',
            name='users',
            field=models.ManyToManyField(related_name='equipmentusagerecord_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
