# Generated by Django 3.0.8 on 2021-04-20 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0012_auto_20210420_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenthistoricalrecord',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipmenthistoricalrecord', to=settings.AUTH_USER_MODEL),
        ),
    ]
