# Generated by Django 3.0.8 on 2021-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_auto_20210420_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name_brief',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
