# Generated by Django 3.0.8 on 2021-04-23 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0015_auto_20210421_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentHistoricalRecord',
            new_name='EquipmentModifyRecord',
        ),
        migrations.RenameModel(
            old_name='SensorHistoricalRecord',
            new_name='SensorRecord',
        ),
        migrations.AlterModelOptions(
            name='equipmentmodifyrecord',
            options={'ordering': ['-created_time'], 'verbose_name': 'EquipmentModifyRecord', 'verbose_name_plural': 'EquipmentModifyRecords'},
        ),
        migrations.AlterModelOptions(
            name='sensorrecord',
            options={'ordering': ['-created_time'], 'verbose_name': 'SensorRecord', 'verbose_name_plural': 'SensorRecords'},
        ),
    ]
