# Generated by Django 3.2.3 on 2021-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_rename_name_brief_sensor_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('T', 'Temperature Sensor'), ('H', 'Humidity Sensor')], default='T', max_length=32),
        ),
    ]
