# Generated by Django 3.2.3 on 2021-06-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('℃', 'Celsius'), ('%', 'Percent')], default='℃', max_length=32),
        ),
    ]
