# Generated by Django 3.0.8 on 2024-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_auto_20241216_2132'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['type'], name='sensor_type_80526e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['equipment'], name='sensor_equipme_2c2869_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['created_time'], name='sensor_created_6668fa_idx'),
        ),
    ]
