# Generated by Django 3.0.8 on 2025-04-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_auto_20241216_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('T', 'Temperature Sensor'), ('H', 'Humidity Sensor'), ('CO2', 'CO2 Sensor'), ('CO', 'CO Sensor'), ('O2', 'O2 Sensor'), ('CH4', 'CH4 Sensor'), ('H2S', 'H2S Sensor')], default='T', max_length=32),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('℃', 'Celsius'), ('%', 'Percent'), ('ppm', 'ppm'), ('%VOL', 'VOL'), ('%LEL', 'LEL')], default='℃', max_length=32),
        ),
    ]
